version: '3'

services:
  frontend:
    build: ./frontend
    container_name: test-docker-frontend
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  api:
    build: ./api
    container_name: test-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3000
      - HOST=http://test-docker.com
      - DB_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db

  api_db:
    image: mongo:latest
    container_name: test-docker-api_db
    volumes:
      - mongodb_api:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: test-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

volumes:
  mongodb_api:
